name: Linting

on: [push, pull_request]

jobs:
  lint:
    name: Trying linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - run: bun install

      - run: bun run check
